In [ ]:
 !pip install panel==0.12.6 hvplot==0.7.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: panel==0.12.6 in /usr/local/lib/python3.8/dist-packages (0.12.6)
Requirement already satisfied: hvplot==0.7.3 in /usr/local/lib/python3.8/dist-packages (0.7.3)
Requirement already satisfied: bokeh<2.5.0,>=2.4.0 in /usr/local/lib/python3.8/dist-packages (from panel==0.12.6) (2.4.3)
Requirement already satisfied: tqdm>=4.48.0 in /usr/local/lib/python3.8/dist-packages (from panel==0.12.6) (4.64.1)
Requirement already satisfied: pyviz-comms>=0.7.4 in /usr/local/lib/python3.8/dist-packages (from panel==0.12.6) (2.2.1)
Requirement already satisfied: markdown in /usr/local/lib/python3.8/dist-packages (from panel==0.12.6) (3.4.1)
Requirement already satisfied: pyct>=0.4.4 in /usr/local/lib/python3.8/dist-packages (from panel==0.12.6) (0.4.8)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from panel==0.12.6) (2.28.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.8/dist-packages (from panel==0.12.6) (5.0.1)
Requirement already satisfied: param>=1.10.0 in /usr/local/lib/python3.8/dist-packages (from panel==0.12.6) (1.12.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from hvplot==0.7.3) (1.3.5)
Requirement already satisfied: holoviews>=1.11.0 in /usr/local/lib/python3.8/dist-packages (from hvplot==0.7.3) (1.14.9)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.8/dist-packages (from hvplot==0.7.3) (1.21.6)
Requirement already satisfied: colorcet>=2 in /usr/local/lib/python3.8/dist-packages (from hvplot==0.7.3) (3.0.1)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.8/dist-packages (from bokeh<2.5.0,>=2.4.0->panel==0.12.6) (6.2)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.8/dist-packages (from bokeh<2.5.0,>=2.4.0->panel==0.12.6) (3.0.3)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.8/dist-packages (from bokeh<2.5.0,>=2.4.0->panel==0.12.6) (6.0)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.8/dist-packages (from bokeh<2.5.0,>=2.4.0->panel==0.12.6) (7.1.2)
Requirement already satisfied: typing-extensions>=3.10.0 in /usr/local/lib/python3.8/dist-packages (from bokeh<2.5.0,>=2.4.0->panel==0.12.6) (4.4.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.8/dist-packages (from bokeh<2.5.0,>=2.4.0->panel==0.12.6) (21.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from Jinja2>=2.9->bokeh<2.5.0,>=2.4.0->panel==0.12.6) (2.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging>=16.8->bokeh<2.5.0,>=2.4.0->panel==0.12.6) (3.0.9)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->hvplot==0.7.3) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->hvplot==0.7.3) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas->hvplot==0.7.3) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from bleach->panel==0.12.6) (0.5.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/dist-packages (from markdown->panel==0.12.6) (5.1.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.4->markdown->panel==0.12.6) (3.11.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->panel==0.12.6) (1.24.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests->panel==0.12.6) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->panel==0.12.6) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->panel==0.12.6) (2.10)

In [ ]:
pip install Flask --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: Flask in /usr/local/lib/python3.8/dist-packages (2.2.2)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.8/dist-packages (from Flask) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.8/dist-packages (from Flask) (3.0.3)
Requirement already satisfied: importlib-metadata>=3.6.0 in /usr/local/lib/python3.8/dist-packages (from Flask) (5.1.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.8/dist-packages (from Flask) (8.1.3)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.8/dist-packages (from Flask) (2.2.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=3.6.0->Flask) (3.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from Jinja2>=3.0->Flask) (2.1.1)

In [ ]:
pip install datapane

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: datapane in /usr/local/lib/python3.8/dist-packages (0.15.5)
Requirement already satisfied: altair<5.0.0,>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (4.2.0)
Requirement already satisfied: posthog<3.0.0,>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (2.2.0)
Requirement already satisfied: requests<3.0.0,>=2.19.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (2.28.1)
Requirement already satisfied: datacommons-pandas<0.0.4,>=0.0.3 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.0.3)
Requirement already satisfied: dacite<2.0.0,>=1.0.2 in /usr/local/lib/python3.8/dist-packages (from datapane) (1.7.0)
Requirement already satisfied: importlib_resources<6.0.0,>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (5.10.1)
Requirement already satisfied: stringcase<2.0.0,>=1.2.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (1.2.0)
Requirement already satisfied: pandas<2.0.0,>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (1.3.5)
Requirement already satisfied: vega-datasets<1.0.0,>=0.9.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.9.0)
Requirement already satisfied: boltons<22.0.0,>=20.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (21.0.0)
Requirement already satisfied: validators<0.21.0,>=0.18.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.20.0)
Requirement already satisfied: PyYAML<7.0.0,>=5.4.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (6.0)
Requirement already satisfied: Jinja2<4.0.0,>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (3.0.3)
Requirement already satisfied: click-spinner<0.2.0,>=0.1.8 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.1.10)
Requirement already satisfied: lxml<5.0.0,>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (4.9.2)
Requirement already satisfied: munch<3.0.0,>=2.3.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (2.5.0)
Requirement already satisfied: pyarrow<11.0.0,>=6.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (9.0.0)
Requirement already satisfied: pydantic<2.0.0,>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (1.10.2)
Requirement already satisfied: dominate<3.0.0,>=2.4.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (2.7.0)
Requirement already satisfied: ipynbname<2022.0.0,>=2021.3.2 in /usr/local/lib/python3.8/dist-packages (from datapane) (2021.3.2)
Requirement already satisfied: micawber>=0.5.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.5.4)
Requirement already satisfied: jsonschema<5.0.0,>=3.2.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (4.3.3)
Requirement already satisfied: click<9.0.0,>=7.1.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (8.1.3)
Requirement already satisfied: furl<3.0.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (2.1.3)
Requirement already satisfied: requests-toolbelt<0.10.0,>=0.9.1 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.9.1)
Requirement already satisfied: colorlog<7.0.0,>=4.1.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (6.7.0)
Requirement already satisfied: chardet<6.0.0,>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (5.1.0)
Requirement already satisfied: glom<23.0.0,>=20.11.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (22.1.0)
Requirement already satisfied: tabulate<0.9.0,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.8.10)
Requirement already satisfied: nbconvert<7.0.0,>=6.1.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (6.5.4)
Requirement already satisfied: datacommons<2.0.0,>=1.4.3 in /usr/local/lib/python3.8/dist-packages (from datapane) (1.4.3)
Requirement already satisfied: toolz<0.13.0,>=0.11.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.12.0)
Requirement already satisfied: dulwich<0.21.0,>=0.20.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (0.20.50)
Requirement already satisfied: packaging<22.0.0,>=20.0.0 in /usr/local/lib/python3.8/dist-packages (from datapane) (21.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from altair<5.0.0,>=4.0.0->datapane) (1.21.6)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.8/dist-packages (from altair<5.0.0,>=4.0.0->datapane) (0.4)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from datacommons<2.0.0,>=1.4.3->datapane) (1.15.0)
Requirement already satisfied: urllib3>=1.25 in /usr/local/lib/python3.8/dist-packages (from dulwich<0.21.0,>=0.20.0->datapane) (1.26.13)
Requirement already satisfied: orderedmultidict>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from furl<3.0.0,>=2.0.0->datapane) (1.0.1)
Requirement already satisfied: attrs in /usr/local/lib/python3.8/dist-packages (from glom<23.0.0,>=20.11.0->datapane) (22.1.0)
Requirement already satisfied: face>=20.1.0 in /usr/local/lib/python3.8/dist-packages (from glom<23.0.0,>=20.11.0->datapane) (22.0.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from importlib_resources<6.0.0,>=3.0.0->datapane) (3.11.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.8/dist-packages (from ipynbname<2022.0.0,>=2021.3.2->datapane) (5.3.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from Jinja2<4.0.0,>=3.0.0->datapane) (2.1.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema<5.0.0,>=3.2.0->datapane) (0.19.2)
Requirement already satisfied: nbformat>=5.1 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (5.7.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (0.8.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (4.6.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (1.5.0)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (0.2.2)
Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (2.6.1)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (0.7.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (5.0.1)
Requirement already satisfied: jupyter-core>=4.7 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (5.1.0)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (1.2.1)
Requirement already satisfied: traitlets>=5.0 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (5.7.1)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.8/dist-packages (from nbconvert<7.0.0,>=6.1.0->datapane) (0.7.2)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.8/dist-packages (from jupyter-core>=4.7->nbconvert<7.0.0,>=6.1.0->datapane) (2.6.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.8/dist-packages (from nbclient>=0.5.0->nbconvert<7.0.0,>=6.1.0->datapane) (7.4.8)
Requirement already satisfied: pyzmq>=23.0 in /usr/local/lib/python3.8/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<7.0.0,>=6.1.0->datapane) (24.0.1)
Requirement already satisfied: nest-asyncio>=1.5.4 in /usr/local/lib/python3.8/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<7.0.0,>=6.1.0->datapane) (1.5.6)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.8/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<7.0.0,>=6.1.0->datapane) (6.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<7.0.0,>=6.1.0->datapane) (2.8.2)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.8/dist-packages (from nbformat>=5.1->nbconvert<7.0.0,>=6.1.0->datapane) (2.16.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging<22.0.0,>=20.0.0->datapane) (3.0.9)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas<2.0.0,>=1.1.0->datapane) (2022.6)
Requirement already satisfied: backoff<2.0.0,>=1.10.0 in /usr/local/lib/python3.8/dist-packages (from posthog<3.0.0,>=1.4.0->datapane) (1.11.1)
Requirement already satisfied: monotonic>=1.5 in /usr/local/lib/python3.8/dist-packages (from posthog<3.0.0,>=1.4.0->datapane) (1.6)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.8/dist-packages (from pydantic<2.0.0,>=1.6.0->datapane) (4.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.19.0->datapane) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.19.0->datapane) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.19.0->datapane) (2.1.1)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.8/dist-packages (from validators<0.21.0,>=0.18.0->datapane) (4.4.2)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from bleach->nbconvert<7.0.0,>=6.1.0->datapane) (0.5.1)
Requirement already satisfied: ipython>=5.0.0 in /usr/local/lib/python3.8/dist-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (7.9.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.8/dist-packages (from ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.8/dist-packages (from ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.2.0)
Requirement already satisfied: pexpect in /usr/local/lib/python3.8/dist-packages (from ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (4.8.0)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (2.0.10)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.8/dist-packages (from ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.18.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.8/dist-packages (from ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (57.4.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.8.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.2.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.8/dist-packages (from pexpect->ipython>=5.0.0->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.7.0)

In [ ]:
pip install altair

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: altair in /usr/local/lib/python3.8/dist-packages (4.2.0)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.8/dist-packages (from altair) (4.3.3)
Requirement already satisfied: pandas>=0.18 in /usr/local/lib/python3.8/dist-packages (from altair) (1.3.5)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.8/dist-packages (from altair) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/dist-packages (from altair) (3.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from altair) (1.21.6)
Requirement already satisfied: toolz in /usr/local/lib/python3.8/dist-packages (from altair) (0.12.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema>=3.0->altair) (5.10.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema>=3.0->altair) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema>=3.0->altair) (0.19.2)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from importlib-resources>=1.4.0->jsonschema>=3.0->altair) (3.11.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.18->altair) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.18->altair) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=0.18->altair) (1.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from jinja2->altair) (2.1.1)

In [ ]:
pip install nsepy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nsepy
  Downloading nsepy-0.8.tar.gz (33 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from nsepy) (4.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from nsepy) (2.28.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from nsepy) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from nsepy) (1.3.5)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from nsepy) (1.15.0)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nsepy) (8.1.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from nsepy) (4.9.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->nsepy) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->nsepy) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->nsepy) (1.26.13)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->nsepy) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests->nsepy) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->nsepy) (2022.12.7)
Building wheels for collected packages: nsepy
  Building wheel for nsepy (setup.py) ... done
  Created wheel for nsepy: filename=nsepy-0.8-py3-none-any.whl size=36085 sha256=8475f07477dba535c12413b1e1a2b04d27bcb7feaa22129581070c6e06ea1f68
  Stored in directory: /root/.cache/pip/wheels/b9/2c/cb/d74199e422a1dbc20297d10cfff9c54d03e0b5c6694d49ccdd
Successfully built nsepy
Installing collected packages: nsepy
Successfully installed nsepy-0.8

In [ ]:
pip install nsepython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nsepython
  Downloading nsepython-0.0.973-py3-none-any.whl (22 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from nsepython) (1.3.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from nsepython) (1.7.3)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from nsepython) (2.28.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->nsepython) (2022.6)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas->nsepython) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->nsepython) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas->nsepython) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->nsepython) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests->nsepython) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->nsepython) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->nsepython) (2022.12.7)
Installing collected packages: nsepython
Successfully installed nsepython-0.0.973

In [ ]:
pip install nsetools

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nsetools
  Downloading nsetools-1.0.11-py3-none-any.whl (9.6 kB)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from nsetools) (1.15.0)
Collecting dateutils
  Downloading dateutils-0.6.12-py2.py3-none-any.whl (5.7 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from dateutils->nsetools) (2.8.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from dateutils->nsetools) (2022.6)
Installing collected packages: dateutils, nsetools
Successfully installed dateutils-0.6.12 nsetools-1.0.11

In [ ]:
pip install GoogleNews

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting GoogleNews
  Downloading GoogleNews-1.6.6-py3-none-any.whl (8.0 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from GoogleNews) (2.8.2)
Collecting dateparser
  Downloading dateparser-1.1.5-py2.py3-none-any.whl (293 kB)
     |████████████████████████████████| 293 kB 4.8 MB/s
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from GoogleNews) (4.6.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from dateparser->GoogleNews) (2022.6)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.8/dist-packages (from dateparser->GoogleNews) (1.5.1)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.8/dist-packages (from dateparser->GoogleNews) (2022.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil->GoogleNews) (1.15.0)
Installing collected packages: dateparser, GoogleNews
Successfully installed GoogleNews-1.6.6 dateparser-1.1.5

In [ ]:
import datapane as dp
import pandas as pd
import altair as alt
from datetime import date
from nsepy import get_history
import pandas as pd
from nsepython import * 
from nsetools import Nse
import requests
import json
import math
from GoogleNews import GoogleNews
nse = Nse()
today_time=datetime.today()

In [ ]:
data=get_history(symbol="NIFTY",start=today_time,end=today_time,index=True,futures=True,expiry_date=date(2023,1,23))
data['Volume']=(data['Number of Contracts']*50*data['Last'])/(data['Last']*1000000)
data1=get_history(symbol="BANKNIFTY",start=today_time,end=today_time,index=True,futures=True,expiry_date=date(2023,1,23))
data1['Volume']=(data['Number of Contracts']*25*data['Last'])/(data['Last']*1000000)
frames = [data, data1]
result = pd.concat(frames)
result['Change in OI']=(result['Change in OI']/result['Open Interest'])
result=result[['Symbol','Volume','Settle Price','Number of Contracts','Open Interest','Change in OI']]
result

,Symbol,Volume,Settle Price,Number of Contracts,Open Interest,Change in OI
Date,,,,,,
2022-12-29,NIFTY,6.93910,18191.00,138782,3013200,-0.499917
2022-12-29,BANKNIFTY,3.46955,43252.35,100478,375575,-1.176729

In [ ]:
data2=nse_fiidii()
data2

    category         date buyValue sellValue  netValue
0     DII **  30-Dec-2022  5715.85   3449.65    2266.2
1  FII/FPI *  30-Dec-2022  2252.66   5203.55  -2950.89

In [ ]:
data=nse.get_index_quote("nifty 200")
data1=nse.get_index_quote("nifty bank")
df1= pd.DataFrame.from_dict(data,orient ='index')
df2= pd.DataFrame.from_dict(data1,orient ='index')
df1.drop
frames = [df1, df2]
result1 = pd.concat(frames,axis=1)
result1

                              0                    0
name                  NIFTY 200           NIFTY BANK
lastPrice               9554.45             42986.45
change                   -32.55              -265.90
pChange                   -0.34                -0.61
imgFileName  NIFTY_200_open.png  NIFTY_BANK_open.png

In [167]:
oi_data, ltp, crontime = oi_chain_builder("NIFTY")

oi_data['PCR']=oi_data['PUTS_OI']/oi_data['CALLS_OI']
oi_data=oi_data[oi_data['CALLS_OI']>0]
oi_data

,CALLS_Chart,CALLS_OI,CALLS_Chng in OI,CALLS_Volume,CALLS_IV,CALLS_LTP,CALLS_Net Chng,CALLS_Bid Qty,CALLS_Bid Price,CALLS_Ask Price,...,PUTS_Ask Price,PUTS_Ask Qty,PUTS_Net Chng,PUTS_LTP,PUTS_IV,PUTS_Volume,PUTS_Chng in OI,PUTS_OI,PUTS_Chart,PCR
1,0.0,1.0,0.0,0.0,0.00,3071.00,0.00,1800.0,3006.15,3083.05,...,0.50,700.0,-0.55,0.45,48.27,7254.0,1174.0,1291.0,0.0,1291.000000
19,0.0,40.0,0.0,0.0,0.00,2159.00,0.00,200.0,2098.25,2183.70,...,1.00,500.0,-0.70,0.90,36.46,38806.0,8065.0,29163.0,0.0,729.075000
23,0.0,20.0,0.0,0.0,0.00,1830.00,0.00,300.0,1892.60,1974.40,...,1.20,4550.0,-0.55,1.20,34.22,2586.0,1045.0,1935.0,0.0,96.750000
29,0.0,96.0,0.0,4.0,66.13,1730.00,8.10,200.0,1613.55,1662.10,...,1.40,100.0,-0.85,1.40,29.71,54365.0,1001.0,40724.0,0.0,424.208333
30,0.0,3.0,3.0,3.0,60.52,1661.10,-128.45,1800.0,1563.50,1638.65,...,1.25,100.0,-0.80,1.25,28.49,1363.0,2.0,312.0,0.0,104.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,0.0,183.0,88.0,429.0,38.12,0.60,-0.45,11550.0,0.60,1.00,...,2886.80,1000.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.000000
117,0.0,207.0,87.0,431.0,39.00,0.65,-0.40,10350.0,0.65,0.75,...,2782.85,1800.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.000000
118,0.0,157.0,18.0,348.0,39.59,0.65,-0.60,950.0,0.65,0.95,...,2833.15,1800.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.000000
119,0.0,18820.0,6032.0,35528.0,39.88,0.60,-0.45,73550.0,0.60,0.65,...,2885.45,1800.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.000000
120,0.0,3727.0,1945.0,7286.0,40.46,0.60,-0.30,19800.0,0.60,0.65,...,2958.35,3600.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.000000

In [ ]:
# Python program to print
# colored text and background
def strRed(skk):         return "\033[91m {}\033[00m".format(skk)
def strGreen(skk):       return "\033[92m {}\033[00m".format(skk)
def strYellow(skk):      return "\033[93m {}\033[00m".format(skk)
def strLightPurple(skk): return "\033[94m {}\033[00m".format(skk)
def strPurple(skk):      return "\033[95m {}\033[00m".format(skk)
def strCyan(skk):        return "\033[96m {}\033[00m".format(skk)
def strLightGray(skk):   return "\033[97m {}\033[00m".format(skk)
def strBlack(skk):       return "\033[98m {}\033[00m".format(skk)
def strBold(skk):        return "\033[1m {}\033[0m".format(skk)

# Method to get nearest strikes
def round_nearest(x,num=50): return int(math.ceil(float(x)/num)*num)
def nearest_strike_bnf(x): return round_nearest(x,100)
def nearest_strike_nf(x): return round_nearest(x,50)

# Urls for fetching Data
url_oc      = "https://www.nseindia.com/option-chain"
url_bnf     = 'https://www.nseindia.com/api/option-chain-indices?symbol=BANKNIFTY'
url_nf      = 'https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY'
url_indices = "https://www.nseindia.com/api/allIndices"

# Headers
headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
            'accept-language': 'en,gu;q=0.9,hi;q=0.8',
            'accept-encoding': 'gzip, deflate, br'}

sess = requests.Session()
cookies = dict()

# Local methods
def set_cookie():
    request = sess.get(url_oc, headers=headers, timeout=5)
    cookies = dict(request.cookies)

def get_data(url):
    set_cookie()
    response = sess.get(url, headers=headers, timeout=5, cookies=cookies)
    if(response.status_code==401):
        set_cookie()
        response = sess.get(url_nf, headers=headers, timeout=5, cookies=cookies)
    if(response.status_code==200):
        return response.text
    return ""

def set_header():
    global bnf_ul
    global nf_ul
    global bnf_nearest
    global nf_nearest
    response_text = get_data(url_indices)
    data = json.loads(response_text)
    for index in data["data"]:
        if index["index"]=="NIFTY 50":
            nf_ul = index["last"]
            print("nifty")
        if index["index"]=="NIFTY BANK":
            bnf_ul = index["last"]
            print("banknifty")
    bnf_nearest=nearest_strike_bnf(bnf_ul)
    nf_nearest=nearest_strike_nf(nf_ul)

# Showing Header in structured format with Last Price and Nearest Strike

def print_header(index="",ul=0,nearest=0):
    print(strPurple( index.ljust(12," ") + " => ")+ strLightPurple(" Last Price: ") + strBold(str(ul)) + strLightPurple(" Nearest Strike: ") + strBold(str(nearest)))

def print_hr():
    print(strYellow("|".rjust(70,"-")))

# Fetching CE and PE data based on Nearest Expiry Date
def print_oi(num,step,nearest,url):
    strike = nearest - (step*num)
    start_strike = nearest - (step*num)
    response_text = get_data(url)
    data = json.loads(response_text)
    currExpiryDate = data["records"]["expiryDates"][0]
    for item in data['records']['data']:
        if item["expiryDate"] == currExpiryDate:
            if item["strikePrice"] == strike and item["strikePrice"] < start_strike+(step*num*2):
                #print(strCyan(str(item["strikePrice"])) + strGreen(" CE ") + "[ " + strBold(str(item["CE"]["openInterest"]).rjust(10," ")) + " ]" + strRed(" PE ")+"[ " + strBold(str(item["PE"]["openInterest"]).rjust(10," ")) + " ]")
                print(data["records"]["expiryDates"][0] + " " + str(item["strikePrice"]) + " CE " + "[ " + strBold(str(item["CE"]["openInterest"]).rjust(10," ")) + " ]" + " PE " + "[ " + strBold(str(item["PE"]["openInterest"]).rjust(10," ")) + " ]")
                strike = strike + step

# Finding highest Open Interest of People's in CE based on CE data         
def highest_oi_CE(num,step,nearest,url):
    strike = nearest - (step*num)
    start_strike = nearest - (step*num)
    response_text = get_data(url)
    data = json.loads(response_text)
    currExpiryDate = data["records"]["expiryDates"][0]
    max_oi = 0
    max_oi_strike = 0
    for item in data['records']['data']:
        if item["expiryDate"] == currExpiryDate:
            if item["strikePrice"] == strike and item["strikePrice"] < start_strike+(step*num*2):
                if item["CE"]["openInterest"] > max_oi:
                    max_oi = item["CE"]["openInterest"]
                    max_oi_strike = item["strikePrice"]
                strike = strike + step
    return max_oi_strike

# Finding highest Open Interest of People's in PE based on PE data 
def highest_oi_PE(num,step,nearest,url):
    strike = nearest - (step*num)
    start_strike = nearest - (step*num)
    response_text = get_data(url)
    data = json.loads(response_text)
    currExpiryDate = data["records"]["expiryDates"][0]
    max_oi = 0
    max_oi_strike = 0
    for item in data['records']['data']:
        if item["expiryDate"] == currExpiryDate:
            if item["strikePrice"] == strike and item["strikePrice"] < start_strike+(step*num*2):
                if item["PE"]["openInterest"] > max_oi:
                    max_oi = item["PE"]["openInterest"]
                    max_oi_strike = item["strikePrice"]
                strike = strike + step
    return max_oi_strike

set_header()
print('\033c')
print_hr()
print_header("Nifty",nf_ul,nf_nearest)
print_hr()
print_oi(10,50,nf_nearest,url_nf)
print_hr()
print_header("Bank Nifty",bnf_ul,bnf_nearest)
print_hr()
print_oi(10,100,bnf_nearest,url_bnf)
print_hr()

# Finding Highest OI in Call Option In Nifty
nf_highestoi_CE = highest_oi_CE(10,50,nf_nearest,url_nf)

# Finding Highet OI in Put Option In Nifty
nf_highestoi_PE = highest_oi_PE(10,50,nf_nearest,url_nf)

# Finding Highest OI in Call Option In Bank Nifty
bnf_highestoi_CE = highest_oi_CE(10,100,bnf_nearest,url_bnf)

# Finding Highest OI in Put Option In Bank Nifty
bnf_highestoi_PE = highest_oi_PE(10,100,bnf_nearest,url_bnf)


print(strCyan(str("Major Support in Nifty:")) + str(nf_highestoi_CE))
print(strCyan(str("Major Resistance in Nifty:")) + str(nf_highestoi_PE))
print(strPurple(str("Major Support in Bank Nifty:")) + str(bnf_highestoi_CE))
print(strPurple(str("Major Resistance in Bank Nifty:")) + str(bnf_highestoi_PE))

In [ ]:
nse_top_gain=nse_get_top_gainers()
nse_top_gain=nse_top_gain[['symbol','open','dayHigh','dayLow','lastPrice','previousClose','change','pChange']]
nse_top_gain

,symbol,open,dayHigh,dayLow,lastPrice,previousClose,change,pChange
0,SHRIRAMFIN,1330,1384.8,1325.15,1381,1312.25,68.75,5.24
1,MANAPPURAM,112.15,117.5,112.15,116.3,111.45,4.85,4.35
2,IDFC,79.15,82,78.85,81.5,78.55,2.95,3.76
3,CANBK,323.45,336.7,321.35,333.05,321.15,11.90,3.71
4,IDFCFIRSTB,57.55,59.5,57.2,58.85,56.75,2.10,3.70

In [ ]:
key = "NIFTY"
key = "BANKNIFTY"
key = "SME"
key = "FO"
key = "OTHERS"
key = "ALL"

def nse_preopen(key="NIFTY"):
    payload = nsefetch("https://www.nseindia.com/api/market-data-pre-open?key="+key+"")    
    return payload


#df6
dictnew={}

converted=''
dictnew=nse_preopen("NIFTY")['data']

df6 = pd.DataFrame(dictnew) 

df6=df6.head(10)
df6

,metadata,detail
0,"{'symbol': 'TATAMOTORS', 'identifier': 'TATAMO...",{'preOpenMarket': {'preopen': [{'price': 347.3...
1,"{'symbol': 'BAJAJFINSV', 'identifier': 'BAJAJF...",{'preOpenMarket': {'preopen': [{'price': 1360....
2,"{'symbol': 'DIVISLAB', 'identifier': 'DIVISLAB...","{'preOpenMarket': {'preopen': [{'price': 3390,..."
3,"{'symbol': 'TATASTEEL', 'identifier': 'TATASTE...",{'preOpenMarket': {'preopen': [{'price': 100.6...
4,"{'symbol': 'TECHM', 'identifier': 'TECHMEQN', ...",{'preOpenMarket': {'preopen': [{'price': 911.9...
5,"{'symbol': 'HINDALCO', 'identifier': 'HINDALCO...",{'preOpenMarket': {'preopen': [{'price': 422.9...
6,"{'symbol': 'AXISBANK', 'identifier': 'AXISBANK...",{'preOpenMarket': {'preopen': [{'price': 841.1...
7,"{'symbol': 'INFY', 'identifier': 'INFYEQN', 'p...",{'preOpenMarket': {'preopen': [{'price': 1365....
8,"{'symbol': 'CIPLA', 'identifier': 'CIPLAEQN', ...",{'preOpenMarket': {'preopen': [{'price': 978.8...
9,"{'symbol': 'BAJFINANCE', 'identifier': 'BAJFIN...",{'preOpenMarket': {'preopen': [{'price': 6185....

In [158]:
 !git clone https://github.com/datapane/dp-template-social-media-dashboard.git

Cloning into 'dp-template-social-media-dashboard'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 49 (delta 21), reused 40 (delta 15), pack-reused 0
Unpacking objects: 100% (49/49), done.

In [ ]:
gn = GoogleNews()
s = gn.search('Nifty 200 and sectoral indices')
txt=gn.get_texts()
lin=gn.get_links()
t=''


for i in range(4):
 t=t+txt[i]
 t=t+'\n'
 t=t+'Read for more, on Link:  '+lin[i]+'\n'
 t=t+'-------------'+'\n'
print(t)

['Share Market Highlights: Nifty ends tad below 18200, Sensex in green, Bank Nifty recovers 762 pts on F&O expiry', 'Share Market Highlights: Nifty, Sensex extend losses for third session, end mild in red amid Covid-19 fears; M&M top loser', 'Block Deal: Ajanta Pharma Promoter Group entities to sell 4.56% stake in company for Rs 650 crore', 'Indices pare losses, close flat; IT, Metal, Oil & Gas bounce back | Mint', 'The Fed effect', 'Share Market Highlights: Sensex ends more than 200 pts lower, Nifty settles below 18,600; hawkish RBI tone drags', 'Sensex Falls More Than 200 Points, Nifty Below 18,700: Market Wrap', 'Share Market Highlights: Nifty, Sensex end flat, Bank Nifty closes up 210 pts; Reliance Industries leads loss', 'ICICI Prudential Nifty Pharma Index Fund: Aims to Capture Growth of Pharma Stocks?', 'Closing Bell: Sensex, Nifty end at record closing high led by oil & gas stocks; metals drag']
Share Market Highlights: Nifty ends tad below 18200, Sensex in green, Bank Nifty recovers 762 pts on F&O expiry
Read for more, on Link:  https://www.financialexpress.com/market/share-market-today-live-updates-sensex-nifty-rupee-vs-dollar-sgx-nifty-in-red-sensex-nifty-may-open-lower-us-asian-markets-down-kfintech-ipo-lists-today-29-december-thursday/2930024/
-------------
Share Market Highlights: Nifty, Sensex extend losses for third session, end mild in red amid Covid-19 fears; M&M top loser
Read for more, on Link:  https://www.financialexpress.com/market/share-market-today-live-updates-sensex-nifty-rupee-vs-dollar-sgx-nifty-in-gree-sula-vineyards-listing-22-december-thursday/2922755/
-------------
Block Deal: Ajanta Pharma Promoter Group entities to sell 4.56% stake in company for Rs 650 crore
Read for more, on Link:  https://economictimes.indiatimes.com/markets/stocks/live-blog/bse-sensex-today-live-nifty-stock-market-updates-21-december-2022/liveblog/96384779.cms
-------------
Indices pare losses, close flat; IT, Metal, Oil & Gas bounce back | Mint
Read for more, on Link:  https://www.livemint.com/market/live-blog/share-market-live-updates-sensex-nifty-bse-nse-stock-market-today-20-12-2022-11671497674881.html
-------------

In [171]:
gn1 = GoogleNews()
s1 = gn1.search('ADR and GDR moves')
txt1=gn1.get_texts()
lin1=gn1.get_links()
t1=''


for i in range(2):
 t1=t1+txt1[i]
 t1=t1+'\n'
 t1=t1+'Read for more, on Link:  '+lin[i]+'\n'
 t1=t1+'-------------'+'\n'
print(t1)

The ABCs of ADRs (and GDRs!)
Read for more, on Link:  https://www.financialexpress.com/market/share-market-today-live-updates-sensex-nifty-rupee-vs-dollar-sgx-nifty-in-red-sensex-nifty-may-open-lower-us-asian-markets-down-kfintech-ipo-lists-today-29-december-thursday/2930024/
-------------
How and Why Chinese Firms Are Listing in Europe Now
Read for more, on Link:  https://www.financialexpress.com/market/share-market-today-live-updates-sensex-nifty-rupee-vs-dollar-sgx-nifty-in-gree-sula-vineyards-listing-22-december-thursday/2922755/
-------------

In [177]:
chart = alt.Chart(result).encode(
    x='Symbol',
    y='Volume'
).mark_line().interactive()

chart1 = alt.Chart(nse_top_gain).encode(
    x='symbol',
    y='open'
).mark_line().interactive()



r = dp.App(dp.Media(file="/content/Stock_background_image.jpg"),dp.Text("NSE Updates"),dp.Text("Top News"),dp.Text(t),dp.Text("NSE Market Turnover"),dp.Table(result),dp.Plot(chart),dp.Text("Institutional Flows"),
              dp.Table(data2),
              dp.Text("Nifty 200 and Bank Nifty Summary"),dp.Table(result1),dp.Text("Options Flow"),
              dp.Table(oi_data),dp.Text("Top Gainers and surfers"),
dp.Table(nse_top_gain),dp.Plot(chart1),dp.Text("Major Support in Nifty:"+str(nf_highestoi_CE)),dp.Text("Major Resistance in Nifty:"+ 
                               str(nf_highestoi_PE)),dp.Text("Major Support in Bank Nifty:"+ 
                               str(bnf_highestoi_CE)),dp.Text("Major Resistance in Bank Nifty:"+ 
                             str(bnf_highestoi_PE)),dp.Text("Preopen News"),dp.Table(df6))
r.save(path='report.html')

App saved to ./report.html